In [22]:
import torch

#一维张量
x=torch.arange(12)
y=x.clone()
print(x,y,sep='\n')

#重塑形状
X=x.reshape(3,4)
print(X)

#全0全1
print(torch.zeros(2,3))
print(torch.ones(2,3))

#列表形式
print(torch.tensor([[1,2,3],[3,4,5]]))

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1, 2, 3],
        [3, 4, 5]])


In [24]:
#多张量运算
a=torch.tensor([[1,2,3],[4,5,6]])
b=torch.tensor([[7,8,9],[10,11,12]])
print(a+b,a-b,a*b,a/b,sep='\n')

#张量拼接(按行或按列)
print(torch.cat((a,b),dim=0),torch.cat((a,b),dim=1),sep='\n')

#张量内求和
print(a.sum(axis=1))
print(a.sum(),b.sum(),sep='\n')

#广播机制(形状不同时计算)
c=torch.tensor([[0],[1],[2]])
d=torch.tensor([[0,1]])
print(c,d,c+d,sep='\n')

tensor([[ 8, 10, 12],
        [14, 16, 18]])
tensor([[-6, -6, -6],
        [-6, -6, -6]])
tensor([[ 7, 16, 27],
        [40, 55, 72]])
tensor([[0.1429, 0.2500, 0.3333],
        [0.4000, 0.4545, 0.5000]])
tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])
tensor([[ 1,  2,  3,  7,  8,  9],
        [ 4,  5,  6, 10, 11, 12]])
tensor([ 6, 15])
tensor(21)
tensor(57)
tensor([[0],
        [1],
        [2]])
tensor([[0, 1]])
tensor([[0, 1],
        [1, 2],
        [2, 3]])


In [21]:
#元素访问
T=torch.arange(16).reshape(4,4)
print(T,T[2,2],sep='\n')

#定区间访问
print(T[1:3,1:3])

#不定区间访问
print(T[1:3,::])

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])
tensor(10)
tensor([[ 5,  6],
        [ 9, 10]])
tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
