In [22]:
import torch

#张量的转置
X=torch.arange(16).reshape(4,4)
A=X.clone()
print(X,X.T,sep='\n')

#向量点积
x=torch.arange(4)
y=torch.tensor([2,3,4,5])
print(torch.dot(x,y))

#矩阵乘以向量
print(torch.mv(A,x))

#矩阵乘法
matrix_a=torch.tensor([[1,2,3],[4,5,6]])
matrix_b=matrix_a.clone().reshape(3,2)
matrix_mul=torch.mm(matrix_a,matrix_b)
print(matrix_a,matrix_b,matrix_mul,sep='\n')

#范数(模长) 
u=torch.tensor([0.0,1.0,2.0,3.0])
print(torch.norm(u)) ##对矩阵也适用
print(torch.abs(u).sum())

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])
tensor([[ 0,  4,  8, 12],
        [ 1,  5,  9, 13],
        [ 2,  6, 10, 14],
        [ 3,  7, 11, 15]])
tensor(26)
tensor([14, 38, 62, 86])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[22, 28],
        [49, 64]])
tensor(3.7417)
tensor(6.)
